# Meta
title: Mark Rothermel
url: rothermel.me
tagline: "My personal webpage."
description: "ML Researcher, focusing on Explainable AI. Thinker. Photographer. Designer."

# Setup
baseurl: ""
permalink: pretty

paginate: 2
paginate_path: "/blog/page:num/"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - .idea
  - node_modules

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Mark Rothermel
  url: https://twitter.com/real_maggi

# Custom vars
version: 0.1.0

# Navbar page list
nav:
  - title: About
    url: /about

  - title: Projects
    url: /projects

  - title: Blog
    url: /blog

  - title: Photography
    url: /photography

  - title: Contact
    url: /contact

defaults:
  - scope:
      path: ""
    values:
      image: https://rothermel.me/assets/images/thumbnail.jpg
#  - scope:
#      path: "/posts/"
#    values:
#      excerpt_separator: <!-- teaser-end -->
